### ISSUE TITLE
Uncaught Error: panicked at 'capacity overflow'

### ISSUE THREAD

**Issue by wirednkod** [paritytech/smoldot#1019]
7 extra bootnodes were added for polkadot and kusama.

After some tests trying to connect with substrate-connect the following error appeared:
```
197.7e33dde3.js:2 Uncaught Error: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:546:5
    at throw (197.7e33dde3.js:2)
    at <anonymous>:wasm-function[892]:0x94bfd
    at <anonymous>:wasm-function[3419]:0x2a308a
    at <anonymous>:wasm-function[3408]:0x2a28cf
    at <anonymous>:wasm-function[3407]:0x2a2850
    at <anonymous>:wasm-function[3418]:0x2a2fa2
    at <anonymous>:wasm-function[3504]:0x2acfd0
    at <anonymous>:wasm-function[3486]:0x2a921f
    at <anonymous>:wasm-function[3472]:0x2a839d
    at <anonymous>:wasm-function[2011]:0x188aff
```

**Comment by wirednkod** [comment]
> 7 extra bootnodes were added for polkadot and kusama.
> 
> After some tests trying to connect with substrate-connect the following error appeared:
> 
> ```
> 197.7e33dde3.js:2 Uncaught Error: panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:546:5
>     at throw (197.7e33dde3.js:2)
>     at <anonymous>:wasm-function[892]:0x94bfd
>     at <anonymous>:wasm-function[3419]:0x2a308a
>     at <anonymous>:wasm-function[3408]:0x2a28cf
>     at <anonymous>:wasm-function[3407]:0x2a2850
>     at <anonymous>:wasm-function[3418]:0x2a2fa2
>     at <anonymous>:wasm-function[3504]:0x2acfd0
>     at <anonymous>:wasm-function[3486]:0x2a921f
>     at <anonymous>:wasm-function[3472]:0x2a839d
>     at <anonymous>:wasm-function[2011]:0x188aff
> ```

When trying to connect with SmoldotProvider I no longer receive a Granda sync message (concerning Polkadot and Kusama)
When trying to connect with ExtensionProvider I receive a Granda sync message but there is no apparent connectivity (probably westend is the one that gives the Grandpa is finished on this case)

**Comment by tomaka** [comment]
This is unfortunately impossible to debug without debug symbols.

**Comment by tomaka** [comment]
This doesn't seem to be happening anymore :shrug:
