### ISSUE TITLE
Unable to select nominees while connected to the lite client

### ISSUE THREAD

**Issue by lovelaced** [paritytech/smoldot#1095]
I was attempting to add nominees for an account on Westend while connected to the light client and the Candidates box appeared completely empty. The "Waiting" tab also didn't list any validators.

Could this be to do with the pruning level of the node that it's connected to (default pruning)? That's the only thing I could come up with.

**Comment by tomaka** [comment]
Most likely fixed by https://github.com/paritytech/smoldot/pull/2491, although I've never tried to reproduce

**Comment by wirednkod** [comment]
> Most likely fixed by #2491, although I've never tried to reproduce

Tried to reproduce with 0.6.21 and I can verify that now it is fixed.
