### ISSUE TITLE
Considering Wasmer

### ISSUE THREAD

**Issue by olanod** [paritytech/smoldot#1353]
Wasmer [prides itself](https://wasmer.io/wasmer-vs-wasmtime) of being a lighter weight, faster and in general more flexible alternative to Wasmtime and other WASM runtimes. Smoldot main focus being its lightweightness  could benefit form such runtime? Running precompiled WASM at basically native speed sounds very appealing for  small embedded use cases like an experiment where I'm trying to pack a node plus a [Matrix server](https://gitlab.com/famedly/conduit) in a pi-zero like board.

**Comment by tomaka** [comment]
It's true that, at least in principle, Wasmer should work as well.
I don't think it's significantly more lightweight than wasmtime, though. They say they can be very light, but only if you use their engine that executes pre-compiled Wasm blobs. I assume that most of the heaviness of wasmtime comes from cranelift, and wasmer would need to use cranelift or LLVM as well.

**Comment by olanod** [comment]
True, at the moment they have [3 different backends](https://docs.wasmer.io/integrations/rust#published-crates) and I imagine their cranelift backend wouldn't be much different from wasmtime's but still is interesting to consider as it provides an extra backend(LLVM), assuming their singlepass is comparable(probably better) to wasmi and on top you get the unified and simpler API that would be something less to maintain.  

The LLVM compiler option still sounds quite appealing to me 🤔 and there could be ways to benefit from it, being slow to compile means you don't want to hot compile it when there's a runtime upgrade in low-end hardware but a big full node could afford bundling all the different compilers and do heavy compilation in the background?  
Maybe another option to transfer those benefits to the low-end hardware, assuming the compilation is deterministic(and probably a separate issue for Substrate), would be if the WASM blob of the runtime isn't part of the storage trie but its a hash. I think I've seen that discussed before but an extra thing to add could be if the chain keeps track of not only a wasm version but also possible variants that are precompiled to different target architectures, even more interesting and more off-topic if the chain keeps track of the runtime as a tree of dependencies so the poor tiny Pi some day would only fetch a tiny optimized binary blob of the only one pallet that changed.

**Comment by tomaka** [comment]
Going to close this. If we were starting from scratch, I would compare wasmtime and wasmer, but right now wasmtime is working well and I don't see any compelling reason to switch to wasmer.
