### ISSUE TITLE
Make it produce blocks

### ISSUE THREAD

**Issue by tomaka** [paritytech/smoldot#194]
Here's a small roadmap before a node can produce blocks:

- [x] Change a bit `sync::full_optimistic` to allowing access to the various caches regarding the best block (virtual machine, storage, merkle root calculation).
- [x] Add the code in `author` that claims a slot and seals the block (https://github.com/paritytech/substrate-lite/pull/247)
- [x] Add a transaction pool (#11)
- [x] Add a keystore (#154)
- [x] Finish the networking to allow to gossiping out the newly-created block.
- [x] Finish the networking to allow to answering incoming block requests about the newly-created block.
- [x] Change `sync_service.rs` to pause the sync'ing during a claimable slot and instead produce a new block.
- [ ] In the future, support offchain workers (#73). Because of the imonline mechanism, we'd get slashed without offchain workers.

**Comment by melekes** [comment]
Can we close this?

**Comment by tomaka** [comment]
Yeah, block production is still quite buggy but this is all covered by TODOs in the code and it doesn't make sense to leave an issue open without anything actionable in it.
