### ISSUE TITLE
Add a way to dry run an extrinsic on his local light node

### ISSUE THREAD

**Issue by librelois** [paritytech/smoldot#1995]
The new rpc method `chainHead_unstable_call` allows end user applications to execute any runtime API locally, that's awesome!

But this new RPC method comes with a too limiting restriction: the called runtime API must not try to modify the storage.
Indeed, the runtime API is executed in a "read only" mode, which returns an error if the runtime try to write to the storage: https://github.com/paritytech/smoldot/blob/main/src/executor/read_only_runtime_host.rs#L359

I have a very specific use case that requires this limitation to be lifted: allowing the end user application to simulate the execution of an extrinsic before actually submitting it to the blockchain.

Full nodes already exposes an RPC method `system_dryRun`, but it is on the one hand unsafe, so not publicly exposed, and on the other hand the purpose of a light node is not to need to trust a remote full node.

In practice, it's not a problem if a locally executed runtime API try to modify the storage, just forget about its modifications after the execution.

I see 2 possible solutions: 

1. Change the implementation of `chainHead_unstable_call` to use `runtime_host` instead of `read_only_runtime_host`, just drop `storage_top_trie_changes` once the execution is finished.
2. Create a new method that does the same thing as `chainHead_unstable_call` but with the executor `runtime_host` instead of `read_only_runtime_host`. This 2nd method can be prefixed with `sudo_` if it's not desirable that a public full node expose it.

**Comment by tomaka** [comment]
Good find, that's indeed a mistake. Option 1 is what is intended.

**Comment by librelois** [comment]
> Option 1 is what is intended.

I think it totally makes sense in the context of a local light node, but it seems questionable in the context of an externally accessible full node.

I understand that smoldot could also be used as a full node in the long run, do you think that the `chainHead` group should only be implemented by light nodes? Or do you expect it can be implemented by full nodes too?

**Comment by tomaka** [comment]
I don't see why this would be questionable in a full node.

**Comment by librelois** [comment]
> I don't see why you think this would be questionable in a full node.

Because with the arrival of jsonrpsee, fullnodes will be able to quantify the resources needed for each RPC method.
But I don't see how a full node can quantify the resources needed for a runtime API call that it doesn't know.
It would be necessary to allow the full node to filter the name of the runtime API and to accept only those that are known and benchmarked.
However, I think that a local lignt node should accept any runtime API, known or not, because it' s local use doesn't have the same problematics.
