### ISSUE TITLE
Transactions are reported as invalid after they've been included

### ISSUE THREAD

**Issue by tomaka** [paritytech/smoldot#2044]
Example logs:

> [10:03:38.360] [tx-service-westend2] Successfully validated transaction 0x2fdd…3889
> [10:03:54.299] [tx-service-westend2] Discarding invalid transaction 0x2fdd…3889: Invalid(Stale)

The transaction actually got included in a block between the two lines.

It seems that something is wrong with the transactions pool, as it's not supposed to be revalidated.

**Comment by wirednkod** [comment]
Some logs:
[dropped_tx.log](https://github.com/paritytech/smoldot/files/8079876/dropped_tx.log)

**Comment by tomaka** [comment]
The revalidation happens because the block it is validated against got finalized and thus pruned from the transactions pool. This by itself is wrong, as validations should be kept in "cache".
