### ISSUE TITLE
generate_chain_spec doesn't work on most of chains

### ISSUE THREAD

**Issue by Asmadek** [paritytech/smoldot#2130]
Hello! 

`generate_chain_spec.sh` script doesn't work on most of chains.

Is there alternative way to receive chain spec?

**Comment by tomaka** [comment]
Hi,

The script should work if you start your node with `--rpc-methods unsafe`
We've recently merged https://github.com/paritytech/substrate/pull/10832, and it should also work no matter what if your Substrate version includes this PR

**Comment by Asmadek** [comment]
@tomaka thank you for explanation
