### ISSUE TITLE
Block already unpinned error

### ISSUE THREAD

**Issue by wirednkod** [paritytech/smoldot#2147]
An error appeared during zombienet tests in substrate connect
```
Error: panicked at 'block already unpinned', /__w/smoldot/smoldot/bin/light-base/src/runtime_service.rs:779:17
```
Logs can be found [here](https://github.com/paritytech/substrate-connect/runs/5571696271?check_suite_focus=true#step:7:911)

**Comment by tomaka** [comment]
I believe it's already been fixed in https://github.com/paritytech/smoldot/pull/2106, which hasn't been released yet

**Comment by tomaka** [comment]
Should be fixed in v0.6.5

**Comment by wirednkod** [comment]
Still happens in 0.6.9:
```
background.js:1 Smoldot has panicked while executing task `json-rpc-adz_rococo`. This is a bug in smoldot. Please open an issue at https://github.com/paritytech/smoldot/issues with the following message:
Error: Uncaught Error: panicked at 'block already unpinned', /__w/smoldot/smoldot/bin/light-base/src/runtime_service.rs:779:17
smoldot.js:2 Uncaught Error: panicked at 'block already unpinned', /__w/smoldot/smoldot/bin/light-base/src/runtime_service.rs:779:17
```

**Comment by tomaka** [comment]
I need logs!

**Comment by wirednkod** [comment]
> I need logs!

Logs in description are not enough?

**Comment by tomaka** [comment]
The logs in the OP were done with an old version of smoldot, and I did actually fix a pretty big issue, so if you've got more recent logs that would guarantee me that I'm not investigating the bug that's already been fixed

**Comment by wirednkod** [comment]
Will reproduce and provide the logs

**Comment by tomaka** [comment]
Problem is that the fix in https://github.com/paritytech/smoldot/pull/2106 is wrong and doesn't properly detect duplicate blocks
