### ISSUE TITLE
"Invalid subscription" panic in runtime_service

### ISSUE THREAD

**Issue by tomaka** [paritytech/smoldot#2190]
When starting the demo and connecting to Polkadot, Kusama and Westend all together, I occasionally have a panic here: https://github.com/paritytech/smoldot/blob/1b229e95973e99baeee22c70592f4cdb25bb71a8/bin/light-base/src/runtime_service.rs#L403

**Comment by melekes** [comment]
> The problem is that, in parallel, another piece of code on top of the runtime service isn't aware of the fact that the subscription has been killed and tries to use the pinned blocks.

Is the solution for "another piece of code" to check if the block they are trying to use is still pinned or not?

**Comment by tomaka** [comment]
This is a good solution from the point of view of the runtime service, but it's not clear to me whether the API users would be able to handle this error properly.
