### ISSUE TITLE
Security vulnerability

### ISSUE THREAD

**Issue by guidovranken** [paritytech/smoldot#2269]
I recently submitted a report to bugbounty@parity.io. I'm getting the impression that this address is not being monitored. Can you please check? Thanks

**Comment by tomaka** [comment]
Hi! This email address is monitored, I got pinged about the issue last Friday (April 29th). The fact that nobody came back to you is a small fuck-up, sorry. Normally you should get an answer soon.

**Comment by guidovranken** [comment]
No problem. When will I receive a response? Thanks

**Comment by guidovranken** [comment]
I've received a response.
