### ISSUE TITLE
Smoldot Crash during statemine/statemint tests

### ISSUE THREAD

**Issue by wirednkod** [paritytech/smoldot#2407]
While talking with @PierreBesson , he mentioned that during various tests that he was performing, for connecting light client with Statemine (using Substrate connect) the following errors appeared:

![smoldot crash](https://user-images.githubusercontent.com/5408605/174625057-32b66b91-8e71-4d34-900d-8972ee50ae30.png)

**Comment by tomaka** [comment]
What I think happens is:

- We queue a parahead fetching operation, but the operation doesn't start immediately.
- The block whose parahead we are fetching gets pruned. The code currently unpins the block.
- The fetching operation gets executed. The panics happens because the block is unpinned.

**Comment by wirednkod** [comment]
> What I think happens is:
> 
> * We queue a parahead fetching operation, but the operation doesn't start immediately.
> * The block whose parahead we are fetching gets pruned. The code currently unpins the block.
> * The fetching operation gets executed. The panics happens because the block is unpinned.

Fwiw this is an error thrown during multiple local tests, Pierre was trying to connect to statemint/statemine

**Comment by tomaka** [comment]
My diagnostic is wrong. The pruning is done after the parahead fetch operation.

**Comment by tomaka** [comment]
I have no idea what causes this, but https://github.com/paritytech/smoldot/pull/2631 improves the error message.
It might also have been accidentally fixed by a couple of PRs since then.
I'm going to close this issue, please open a new one if you have a similar error.
