### ISSUE TITLE
Consider replacing ed25519-zebra with ed25519-consensus

### ISSUE THREAD

**Issue by tomaka** [paritytech/smoldot#2446]
https://docs.rs/ed25519-consensus/latest/ed25519_consensus/

For the reason that `ed25519-zebra` seems unmaintained.

**Comment by burdges** [comment]
I'm afraid curve25519-dalek and curve25519-dalek-ng are both relatively unmaintained, but more people care about the former, so maybe better odds it gets maintained, so I concluded zebra makes the most sense.

**Comment by tomaka** [comment]
Closing, then
