### ISSUE TITLE
Panic in runtime call after upgrade

### ISSUE THREAD

**Issue by tomaka** [paritytech/smoldot#2468]
Trying to send a transaction after a runtime upgrade happened has led to:

> Error: panicked at 'called `Result::unwrap()` on an `Err` value: Call(StorageQuery(StorageQueryError { errors: [ProofVerification(TrieRootNotFound), ProofVerification(TrieRootNotFound), ProofVerification(TrieRootNotFound)] }))', /home/tomaka/Projets/smoldot/bin/light-base/src/json_rpc_service/state_chain.rs:1188:26
> (demo) Error during JSON-RPC request: Error: Error: panicked at 'called `Result::unwrap()` on an `Err` value: Call(StorageQuery(StorageQueryError { errors: [ProofVerification(TrieRootNotFound), ProofVerification(TrieRootNotFound), ProofVerification(TrieRootNotFound)] }))', /home/tomaka/Projets/smoldot/bin/light-base/src/json_rpc_service/state_chain.rs:1188:26

**Comment by tomaka** [comment]
https://github.com/paritytech/smoldot/blob/84745accd5608c98ceb4e3d6733e573808e442ad/bin/light-base/src/json_rpc_service/state_chain.rs#L1188

**Comment by wirednkod** [comment]
Omni reported the following:
![image](https://user-images.githubusercontent.com/5408605/186389802-efc7c21a-3759-40c6-b06e-5545cad62606.png)

I think this is relevant to this issue

**Comment by pgolovkin** [comment]
@tomaka when the release may be expected?

**Comment by tomaka** [comment]
https://github.com/paritytech/smoldot/pull/2745
