### ISSUE TITLE
Support state_traceBlock

### ISSUE THREAD

**Issue by xlc** [paritytech/smoldot#2518]
It is super useful to be able to replay block and fetch all changed storages for that particular block

https://github.com/paritytech/substrate/pull/9642

**Comment by tomaka** [comment]
There are a couple of issues with that:

- The spans require a runtime specifically compiled for tracing. Smoldot will never support that, as it always fetches the runtime from the chain (the only exceptions being `codeSubstitutes` in the chain spec)
- It would require implementing parsing the metadata in smoldot.

It seems to me that `state_traceBlock` could be replaced with a more generic version of `state_call` that returns the list of storage changes, and leaving to the frontend the task of turning these changes into events. But that's out of scope of this repo.

**Comment by xlc** [comment]
All I really need is all the changed storages within a given block so the tracing API is not necessary.
I don't think it is possible to implement a runtime API to do this. On the other hand, I don't know the storage layer details but it maybe possible to simply retrieve those data? Otherwise can always replay the block to collect those information.

**Comment by tomaka** [comment]
> I don't think it is possible to implement a runtime API to do this.

What I mean is that you could use `state_call` to call `Core_execute_block` manually, passing as parameter the header and body of the block. If `state_call` then additionally returned the list of changes in the storage, that would have the same effect as `state_traceBlock`.

**Comment by xlc** [comment]
Ok so we need a version of state_call that returns changed storages a have a new rpc call does that? Should I make an issue to Substrate get have it implemented there first and then follow up here?

**Comment by tomaka** [comment]
No, IMO any extension to the JSON-RPC API should go in https://github.com/paritytech/json-rpc-interface-spec/

However there's another problem with the idea of using `state_call("Core_execute_block", ...)`, which is that the frontend would need to manually tweak the header to remove the seal.

I think I'll just add `state_traceBlock` to smoldot.

**Comment by xlc** [comment]
This actually requires wasm override which just doesn't make sense on light client so I will close this.
