### ISSUE TITLE
JS demo returns `Error while adding chain: Error: Data error`

### ISSUE THREAD

**Issue by wirednkod** [paritytech/smoldot#2523]
When running the demo, it is always returned:
```
Error while adding chain: Error: Data error
```
This seems to be coming from the `tiny-inflate` and specifically from [here](https://github.com/paritytech/smoldot/blob/main/bin/wasm-node/javascript/src/tiny-inflate/index.js#L330) that returns an error due to [invalid length](https://github.com/paritytech/smoldot/blob/main/bin/wasm-node/javascript/src/tiny-inflate/index.js#L298-L300)

**Comment by tomaka** [comment]
This should only happen if you had cloned the repo before https://github.com/paritytech/smoldot/pull/2506 and didn't run `prepare.mjs` since then

**Comment by tomaka** [comment]
Managed to reproduce. Have no idea what the problem is. Decoding the base64 and re-inflating the buffer within `prepare.mjs` using `zlib` works fine.

I'll restore pako after https://github.com/paritytech/smoldot/pull/2522
