### ISSUE TITLE
Documentation for a light client completely in Rust

### ISSUE THREAD

**Issue by arrudagates** [paritytech/smoldot#2542]
I've been trying for quite a while to get light_base working without the JavaScript side, but my knowledge of JavaScript is not good enough to port that code over to the rust side of the example. If possible, I'd greatly appreciate an example like that without the JavaScript side and completely in Rust, as it's not just for web apps that light clients can be used for!

**Comment by tomaka** [comment]
The documentation of the `Platform` trait are normally good enough that you shouldn't have to read the JS code.
Feel free to point out things that you don't understand in that documentation.

**Comment by arrudagates** [comment]
> The documentation of the `Platform` trait are normally good enough that you shouldn't have to read the JS code. Feel free to point out things that you don't understand in that documentation.

I've tried my best to understand, but I have no idea what those functions should be doing and what those types should be set to. Can you just provide a full rust example?

**Comment by gilescope** [comment]
I've had a go and am also a bit perplexed. I had a go: https://github.com/gilescope/dotsamaworld/commit/22566351f594168e51addc7042867423be063d22

I could construct something that compiled, but once I had added my chain and got a chain_id I was uncertain what to do next. Can I ask something for a block or what the latest block number is? An example would make things clearer as to how I can use smoldot once I have constructed it. If anyone else has tried calling smoldot from rust would like to see that code.

**Comment by gilescope** [comment]
Also please let me know if that's definitely NOT the right way to be constructing things - I did not have much to go on and am just following the compiler...

**Comment by tomaka** [comment]
> I've had a go and am also a bit perplexed. I had a go: https://github.com/gilescope/dotsamaworld/commit/22566351f594168e51addc7042867423be063d22

Your `new_task_rx` variable will then receive tasks that must be executed until they finished. You can be implemented basically like that:

```rust
tokio::spawn(async move {
    let mut all_tasks = stream::FuturesUnordered::new();
    loop {
        futures::select! {
            (_, new_task) = new_task_rx.select_next_some() => {
                all_tasks.push(new_task);
            },
            () = all_tasks.select_next_some() => {},
        }
    }
})
```

> Can I ask something for a block or what the latest block number is?

Well, all you need to do is call `Client::json_rpc_request`, passing as parameter the same format as regular JSON-RPC requests.
https://github.com/paritytech/smoldot/blob/2f8d6a270ce8c54cc66e7165a02e9cf537668892/bin/light-base/src/lib.rs#L1020

The responses will be sent to the channel you passed as part of `addChain`.

**Comment by tomaka** [comment]
The biggest challenge is implementing the `Platform` trait.

**Comment by gilescope** [comment]
I can start with copying `bin/wasm-node/rust` and then like drawing an owl, all I have to do is shove `ws_stream_wasm` into it.
