### ISSUE TITLE
Integrate cargo spellcheck in CI

### ISSUE THREAD

**Issue by tomaka** [paritytech/smoldot#255]
https://github.com/drahnr/cargo-spellcheck

**Comment by melekes** [comment]
related issue in `cargo-spellcheck`: https://github.com/drahnr/cargo-spellcheck/issues/15

**Comment by tomaka** [comment]
We can simply do `cargo install cargo-spellcheck` on CI.

**Comment by melekes** [comment]
Install it every time? Not ideal, but I can do it, sure.
