### ISSUE TITLE
Smoldot panic at `addresses.rs`

### ISSUE THREAD

**Issue by wirednkod** [paritytech/smoldot#2568]
While running smoldot client with Substrate Connect extension - after sometime that it operates normally (approx. ~ 1 hour) the following message appears:
```
panicked at 'explicit panic', src/network/service/addresses.rs:107:22
onWasmPanic @ instance.js:37
```

**Comment by tomaka** [comment]
Probably happens if we discover a peer we're already connected to, as in that situation the list of addresses doesn't contain the address of the existing connection(s).
