### ISSUE TITLE
Genesis wasm used for parachains. 

### ISSUE THREAD

**Issue by xlc** [paritytech/smoldot#2591]
Trying with the demo client to connect to Acala and Karura. The `state_getRuntimeVersion` is returning the genesis block wasm. I believe the metadata is also the genesis metadata. Relaychain doesn't have this issue.

**Comment by tomaka** [comment]
I know for sure that it works fine on Statemint and Statemine, as they were only a non-functional shell at the beginning.

Are you sure that you are calling `state_getRuntimeVersion` after the parachain has reached the head of the chain?

The way smoldot behaves is that it will tell you that it's at block 0 (and calling any RPC function such as `state_getRuntimeVersion` will return the information as if you were at block 0), and once it manages to connect to the relay chain it will jump from block 0 to the head of the chain.

**Comment by xlc** [comment]
I just tried for Statemine and isn't working. It is synced to latest block.

<img width="1487" alt="Screen Shot 2022-08-08 at 9 07 43 PM" src="https://user-images.githubusercontent.com/1201310/183382271-24532751-e5e9-44fe-a410-289a142ff8e5.png">
.

**Comment by tomaka** [comment]
Notes for myself: after the warp sync, the sync service downloads the first parahead, and then report that this parahead is a child of the genesis parablock. This is completely wrong.

**Comment by tomaka** [comment]
The logic of the `finalized_parahead` variable is completely wrong. It's unclear to me what I was thinking when implementing this.
