### ISSUE TITLE
How to specify & force peer node?

### ISSUE THREAD

**Issue by xlc** [paritytech/smoldot#2629]
I want to setup new node for that's substrate-connect friendly and need a way to verify it actually works.

How do I make smoldot only connect to a specified node? It will be similar to `--reserved-only --reserved-nodes=xxx` in Substrate.

**Comment by tomaka** [comment]
If you just want to check whether a node is reachable, you can replace all the bootnodes in the chain spec with that single node.

The problem with a "reserved only" mode (or equivalent) in smoldot is that smoldot attempts to merge multiple chains together under the hood. For example, if you add two chains with the same genesis hash, it will most of the time only actually add the chain once and keep two references to that single chain. If there was a "reserved only" mode, one chain could be in reserved mode and the other not, and thus smoldot would no longer be able to de-duplicate these chains.
