### ISSUE TITLE
embeddable native light-client Rust library

### ISSUE THREAD

**Issue by rphmeier** [paritytech/smoldot#2671]
It'd be useful to have some kind of Rust library in this repo which you can link in, pass a chain-spec and some operating parameters, and get an RPC object back. 

Is this something we want in the smoldot repo? Should it live somewhere else?

What architecture would you recommend for this? The bin/wasm-node seems to be a good starting point. 

What should its API be?

**Comment by tomaka** [comment]
If you want to integrate a light client into a Rust application, the library you're looking for is `smoldot-light-base`: https://github.com/paritytech/smoldot/tree/main/bin/light-base

You just have to implement the `Platform` trait found here: https://github.com/paritytech/smoldot/blob/2f1c8e62261c47da01db834b8e6629a528e70b3b/bin/light-base/src/lib.rs#L91

I believe that this is the least opinionated API possible. Anything higher level (for example, sockets handled automatically) and you might run into blockers.

Not that I'm not sure how easy this trait is to implement on a desktop platform.

cc #2542

**Comment by rphmeier** [comment]
I've had a look at the light-base but it's hardly plug-and-play. I guess I'd be looking for something like a `Platform` implementation for a desktop environment which could be combined with the light-base here.

**Comment by rphmeier** [comment]
I'd be happy to contribute an example to the repo of implementing the `Platform` trait for the desktop environment - would `Connection` be a `tokio::TcpStream` in that scenario?

**Comment by tomaka** [comment]
`Stream` would be a `TcpStream`, and `Connection` can be anything (`!` would be the most appropriate, but since it's not stable you can use `()`).

I think the best approach is to make the trait as easy to implement as possible, and then have everyone either implement the trait themselves or copy-paste an existing example.

**Comment by rphmeier** [comment]
Is the platform trait expected to change much in the future? It'd be nice to have more developer resources but we could put something in the substrate.dev site instead.

**Comment by arrudagates** [comment]
> I'd prefer to not add a demo implementation as code in this repo, unless we go for maintaining a proper desktop light client.

As a potential user of a smoldot desktop light client I do think it's desirable to have something like that, unless you want to implement it in a separate repo (like substrate-connect), but I do think we need something that can be easily plugged into subxt like substrate-connect can be plugged into polkadot.js api

**Comment by rphmeier** [comment]
cc https://github.com/paritytech/subxt/issues/596
