### ISSUE TITLE
Panic during token transfer

### ISSUE THREAD

**Issue by wirednkod** [paritytech/smoldot#2680]
While trying to transfer tokens in westend, the following error occurred:
```
panicked at 'explicit panic', /__w/smoldot/smoldot/src/libp2p/peers.rs:1245:18
```
and
```
smoldot.js:2 Uncaught Error: panicked at 'explicit panic', /__w/smoldot/smoldot/src/libp2p/peers.rs:1169:18
    at panic (smoldot.js:2:71832)
    at 00f3e1e6:0x13a715
    at 00f3e1e6:0x5d8f8
    at 00f3e1e6:0x2682b3
    at 00f3e1e6:0x2678c9
    at 00f3e1e6:0x267fba
    at 00f3e1e6:0x272e01
    at 00f3e1e6:0x26df65
    at 00f3e1e6:0xe3afc
    at 00f3e1e6:0xe8344
 ```
 
 EDIT: This seems to happen, only when a transaction is initiated and extension is used. When extension is off this does not happen

**Comment by tomaka** [comment]
[`Peers::peers_list`] needs a refactor after https://github.com/paritytech/smoldot/pull/2610, as it is now ambiguous.
