### ISSUE TITLE
Would be great if there was a smoldot-light example that compiled to wasm32

### ISSUE THREAD

**Issue by gilescope** [paritytech/smoldot#2700]
It would be pretty cool if `cargo build --example basic --target wasm32-unknown-unknown` compiled as then we could use smoldot in the browser. Idk maybe we need two examples - one native with std and one for wasm. That would cover all use cases.

Setting the `std` feature in smoldot-light seems a no no for wasm as that sets `std` in smoldot but the [Platform](https://github.com/paritytech/smoldot/blob/main/bin/light-base/src/platform/async_std.rs) need std enabled and that mostly seems to be because smoldot::libp2p::websocket needs `std`. For a rust/wasm friendly websocket gloo::net::websocket now exists ( https://github.com/rustwasm/gloo/blob/master/crates/net/src/websocket/mod.rs ) and that's maintained by the rust web assembly working group. I concede that it might need a shove to fit in with the current Platform trait but it doesn't need to be pretty - just having that capability would be amazing.

**Comment by tomaka** [comment]
What you're asking for is essentially what is in `bin/wasm-node`

**Comment by gilescope** [comment]
Ok. I'll try and call that from js then...
