### ISSUE TITLE
Error: panicked at 'called `Option::unwrap()` on a `None` value', 

### ISSUE THREAD

**Issue by wirednkod** [paritytech/smoldot#2704]
When trying to replicate the [#1233](https://github.com/paritytech/substrate-connect/issues/1233) issue concerning parachain light client connectivity I got the following error:

> Internal error in smoldot: Error: panicked at 'called `Option::unwrap()` on a `None` value', /__w/smoldot/smoldot/src/transactions/light_pool.rs:515:63

using Substrate Connect Extension with Firefox.

**Comment by tomaka** [comment]
cc https://github.com/paritytech/smoldot/issues/1433

**Comment by tomaka** [comment]
Might be fixed by https://github.com/paritytech/smoldot/pull/2703

**Comment by tomaka** [comment]
After looking more into it, extremely likely to be fixed by #2703, so closing this.
