### ISSUE TITLE
Smoldot has panicked while executing task `connections`

### ISSUE THREAD

**Issue by HCastano** [paritytech/smoldot#2737]
I'm running Smoldot on two browser tabs in Chrome without the Substrate-Connect extension, both running the [Multi Demo](https://paritytech.github.io/substrate-connect/demo/). The first tab syncs the chain fine, but the second ends up hanging with the following error.

```
Smoldot has panicked while executing task `connections`. This is a bug in smoldot. Please open an issue at https://github.com/paritytech/smoldot/issues with the following message:
panicked at 'not yet implemented', /__w/smoldot/smoldot/src/libp2p/connection/yamux.rs:441:29

main.3fb9fca2.js:19 Uncaught CrashError: panicked at 'not yet implemented', /__w/smoldot/smoldot/src/libp2p/connection/yamux.rs:441:29
    at h (main.3fb9fca2.js:19:219391)
    at u.sendJsonRpc (main.3fb9fca2.js:19:222163)
    at t (polkadot.01.1e8f6182.js:1:113203)
```

Refreshing the second tab sometimes seems to help.

**Comment by tomaka** [comment]
This has been fixed in https://github.com/paritytech/smoldot/pull/2682, which has been released in v0.6.31.
I think that this version of smoldot didn't make it upstream yet.
