### ISSUE TITLE
Panic at single_stream

### ISSUE THREAD

**Issue by wirednkod** [paritytech/smoldot#2740]
Got the following error with Smoldot 0.6.32 (latest extension installed 0.6.19)

> Internal error in smoldot: Error: panicked at 'called `Option::unwrap()` on a `None` value', /__w/smoldot/smoldot/src/libp2p/connection/established/single_stream.rs:845:14

**Comment by tomaka** [comment]
https://github.com/paritytech/smoldot/blob/d2c79186249a6f6a5492b01550763985421e1470/src/libp2p/connection/established/single_stream.rs#L856

**Comment by tomaka** [comment]
https://github.com/paritytech/smoldot/blob/d2c79186249a6f6a5492b01550763985421e1470/src/libp2p/collection/single_stream.rs#L328

**Comment by tuul-wq** [comment]
@wirednkod just got an error in the same file, it might be connected to your catch
`@substrate/smoldot-light^0.6.34`

> panicked at 'called `Option::unwrap()` on a `None` value', /__w/smoldot/smoldot/src/libp2p/connection/established/single_stream.rs:859:14
