### ISSUE TITLE
Change the multi-stream connections API

### ISSUE THREAD

**Issue by tomaka** [paritytech/smoldot#2754]
After trying to implement the WebRTC handshake, I've changed my mind on how to design the APIs.

Rather than providing a PeerId (the actual one that's been negotiated), the multi-stream connection opener now just says "this is a libp2p webrtc connection", and the negotiation is done entirely within smoldot.

In the same vain, single-stream connections should also get an extra parameter indicating something like "this needs multistream-select for yamux and noise". In the future, we can also imagine additionally indicating "this is websocket" or "this is websocket secure" and let smoldot do the WebSocket and TLS handshakes.

cc @melekes 
cc https://github.com/paritytech/smoldot/issues/1712

**Comment by melekes** [comment]
Should we then rename 'multi-stream' to 'webrtc-multi-stream'?

**Comment by tomaka** [comment]
I had instead in mind to add a parameter when creating a multistream connection indicating the type (in this case WebRTC)
