### ISSUE TITLE
Panicked at 'called `Result::unwrap()`

### ISSUE THREAD

**Issue by tuul-wq** [paritytech/smoldot#2763]
Got the following error while connected to Polkadot using lates version of `@polkadot/rpc-provider": "9.4.1` / `"@substrate/smoldot-light": "0.6.33"`

> Smoldot has panicked while executing task "json-rpc-polkadot"
> `Panicked at 'called Result::unwrap() on an Err value: ()', /__w/smoldot/smoldot/bin/light-base/src/json_rpc_service.rs:1346:61`

**Comment by tomaka** [comment]
https://github.com/paritytech/smoldot/blob/405c38c395327bc3b834f5c3bedec026ded9fa34/bin/light-base/src/json_rpc_service.rs#L1354
