### ISSUE TITLE
Smoldot Panic Error while connecting to substrate connect

### ISSUE THREAD

**Issue by MohammadAbuzar945** [paritytech/smoldot#2777]
Internal error in smoldot: Error: panicked at 'explicit panic', /__w/smoldot/smoldot/src/network/service.rs:747:29

**Comment by tomaka** [comment]
Is there any specific action that you did that lead to this? I don't know how to reproduce.

**Comment by MohammadAbuzar945** [comment]
I just connect  substrate connect with (light client experimental) in polkadot JsAPI After a minute this error came

**Comment by stepanLav** [comment]
Hello!
I've faced with the same problem, we are using v0.6.34 of smoldot.

I faced with it when my wifi connection was disconnected.

Looks like it happens [here](https://github.com/paritytech/smoldot/blob/7d242834a88ae520f048e1eb3982a00ff95aa6e5/src/network/service.rs#L747)

<details>
  <summary>Spoiler!</summary>
<img width="1624" alt="Screenshot 2022-10-06 at 18 29 14" src="https://user-images.githubusercontent.com/40560660/194532908-77524c5f-5bed-4da2-b990-33c6bf74c94d.png">

</details>
