### ISSUE TITLE
Smoldot freezes browser UI on sync finish

### ISSUE THREAD

**Issue by tuul-wq** [paritytech/smoldot#2786]
In our SPA we use `@polkadot/rpc-provider^9.4.2` to connect 3 `ScProviders`
During the connection UI works fine, but just before `sync finished` message in console we face a 1.2 second freeze.
This happens every time when `sync finished` for 3 chains that we connect with ScProvider - Polkadot, Kusama, Westend.
We're not sending any requests to ScProvider, it just works by itself.
I recorded performance check in Chrome and saw a long wasm function execution
````
(func $func5418 (param $var0 i32) (param $var1 i32)
    (local $var2 i32) (local $var3 i32) (local $var4 i32) (local $var5 i64)
````
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/8149541/192555810-79865f87-97f0-4253-92e2-8386015a992b.png">

Log message example: [sync-service-polkadot] GrandPa warp sync finished to #12229848 (0xea75…6e7b)
`smoldot version 0.6.34`

**Comment by tomaka** [comment]
This is most likely the time it takes to verify the finality proofs.

While there's a "CPU limiter" in place, I suspect that it doesn't work because the inner `FuturesUnordered` immediately re-polls futures that are woken up during their execution.

**Comment by tomaka** [comment]
cc https://github.com/rust-lang/futures-rs/issues/2053

**Comment by tuul-wq** [comment]
@tomaka thanks for the fix, can't wait to see it merged and released ☺️
