### ISSUE TITLE
Smoldot light client has panicked with error - connecting to GM chain

### ISSUE THREAD

**Issue by bemtikru** [paritytech/smoldot#2810]
Internal error in smoldot: Error: panicked at 'called `Option::unwrap()` on a `None` value', /__w/smoldot/smoldot/src/libp2p/connection/established/single_stream.rs:859:14

**Comment by tomaka** [comment]
Thanks.
Closing as duplicate of https://github.com/paritytech/smoldot/issues/2740, which is fixed in smoldot 0.7.0
