### ISSUE TITLE
Kusama connection caused Panic in service.rs

### ISSUE THREAD

**Issue by tuul-wq** [paritytech/smoldot#2841]
Just after I've connected to Kusama network I faces Rust error -
`Error: panicked at 'explicit panic', /__w/smoldot/smoldot/src/network/service.rs:665:29`

<img width="892" alt="image" src="https://user-images.githubusercontent.com/8149541/194584811-c29b551d-90c0-4b56-a0e1-e831df52443a.png">

Library version: `smoldot^0.6.34`

**Comment by tomaka** [comment]
Note for self: https://github.com/tomaka/substrate-lite-1/blob/3b9f1c6a9afcfdda42e6a2b2a9fb2470e9330526/src/network/service.rs#L665

**Comment by tomaka** [comment]
There have been many networking changes since 0.6.34, and I'm performing more clean ups at the moment, so it's unclear if this issue still is one.

**Comment by tuul-wq** [comment]
@tomaka yep, I saw new releases. Thank you for all the fixes, we really appreciate it! 🔥
