### ISSUE TITLE
Unexpected amount of results of `state_getKeysPaged` JSON RPC request (staking.validators)

### ISSUE THREAD

**Issue by wirednkod** [paritytech/smoldot#2946]
When trying to request the `validators` list from both light client and polkadotJS the responses' length is different (light client: 2, while polkadotJS; 996). 

In order to replicate the following method can be called (unfortunately it is truncated in the logs):
> {"id":8,"jsonrpc":"2.0","method":"state_getKeysPaged","params":["0x5f3e4907f716ac89b6347d15ececedca88dcde934c658227ee1dfafcd6e16903",1000,"0x5f3e4907f716ac89b6347d15ececedca88dcde934c658227ee1dfafcd6e16903"]}

PolkadotJS Apps:
<img width="1702" alt="Screenshot 2022-10-29 at 3 15 19 PM" src="https://user-images.githubusercontent.com/5408605/198833596-c3ab81e7-23de-491b-9760-bad3671dbe58.png">

Light Client Apps:
<img width="868" alt="Screenshot 2022-10-29 at 3 14 37 PM" src="https://user-images.githubusercontent.com/5408605/198833600-ebf680b8-fce6-4bf4-bbe4-795b9ecd145f.png">

Logs from the replication are attached: [state_getKeysPaged.txt](https://github.com/paritytech/smoldot/files/9893591/state_getKeysPaged.txt)

[Initiated by this issue on Polkadot Staking Dashboard](https://github.com/paritytech/polkadot-staking-dashboard/issues/300). Based on it, this seems to impact eraStakers, validators, bondedPools and poolMembers entries requests.

**Comment by tomaka** [comment]
I need the actual full-length request
