### ISSUE TITLE
TypeError: api.rpc.net.version is not a function

### ISSUE THREAD

**Issue by gluneau** [paritytech/smoldot#3017]
While this call works with the normal RPC calls, it does not seem to be implemented for the light client.

Is this a bug or a missing feature?

```ts
const rawNetworkPrefix = await api?.rpc.net.version();
```

**Comment by tomaka** [comment]
I have no idea what `rpc.net.version` is even supposed to be.
If PolkadotJS calls a function that isn't supported by smoldot, you'll see an error in the logs, and also an error will be returned to PolkadotJS indicating that it's not supported (making this a PolkadotJS no matter what).

**Comment by gluneau** [comment]
Thanks for looking into this Pierre, I've found the docs for [net_version](https://polkadot.js.org/docs/substrate/rpc/#version-text) and it returns the protocol version and that is the same as [eth_chainId](https://polkadot.js.org/docs/substrate/rpc/#chainid-u64)

So I tried to use `const rawNetworkPrefix = await api?.rpc.eth.chainId();` and got the same similar message `TypeError: api.rpc.eth.chainId is not a function` while using the light rpc service. (Works fine under wss rpc)

```sh
curl --request POST \
     --url https://shiden-rpc.dwellir.com \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '
{
     "id": 1,
     "jsonrpc": "2.0",
     "method": "net_version"
}
'
{"jsonrpc":"2.0","result":"336","id":1}

curl --request POST \
     --url https://shiden-rpc.dwellir.com \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '
{
     "id": 1,
     "jsonrpc": "2.0",
     "method": "eth_chainId"
}
'
{"jsonrpc":"2.0","result":"0x150","id":1}
```
Both provided the same answer.  (0x150 === 336) under wss rpc, and both broke under light rpc

So is it smoldot? or substrate_connect that is not translating the requests?
Can I curl my local substrate_connect?

**Comment by tomaka** [comment]
I don't know how `https://shiden-rpc.dwellir.com` is working, but if I send the request to `rpc.polkadot.io` I get an error about the method not existing. I have no idea where these JSON-RPC functions come from. Substrate doesn't support them.

Are you trying to achieve something specific by calling `rpc.net.version`? This function seems utterly useless to me, and I'm not going to support random JSON-RPC functions just for the sake of returning a dummy "1".

**Comment by tomaka** [comment]
From the point of view of smoldot, the only JSON-RPC functions that it supports are:

- The ones that Substrate supports, and they should be considered deprecated.
- https://paritytech.github.io/json-rpc-interface-spec/, which works.

Sorry for the bad experience, but I'm not in any way responsible for this shitshow and I'm closing as "not my problem"
