### ISSUE TITLE
Call to `chain_getHeader` returns null

### ISSUE THREAD

**Issue by rakanalh** [paritytech/smoldot#337]
Creating this issue here to document my observations:

When trying to call `author_submitExtrinsic` using polkadotJS, the SL node receives 3 calls:

Request 1:
`{"id":8,"jsonrpc":"2.0","method":"state_subscribeStorage","params":[["0x26aa394eea5630e07c48ae0c9558`
Response 1:
```
Response: {"jsonrpc":"2.0","method":"state_storage","params":{"subscription":"1","result":{"block":"0x1474bb43891a2e4f50ecfdf61937ede1d49e7ad188dbfeedec827fe47ad28c15","changes":[["0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9a878be6bb31474b3a62564a1fe0189a8e07f77a9dda9f43d27763f5f6d1883b467bbd237777ddd9063b54e22adb2b816",null]]}}}
```
Request 2:
`{"id":9,"jsonrpc":"2.0","method":"chain_getHeader","params":[]}`
Response:
```
Response: {"jsonrpc":"2.0","id":9,"result":{"parentHash":"0x1474bb43891a2e4f50ecfdf61937ede1d49e7ad188dbfeedec827fe47ad28c15","extrinsicsRoot":"0xb1efb6af6ed24680e628703d77e6657c8d906d5e39ddf89d7fb9364f368cc8ce","stateRoot":"0x1e6d18c7e2c6aee52336100523a915b1bcc8d2a09730bd915478e289ed00174c","number":"0x2fa1ee","digest":{"logs":["0x064241424534020b000000c950f30f00000000","0x05424142450101928b3af0104851b4047fea61ddf96ca98069ded3bd49e710ef669ed8d3a5a27abecb6d1b9f76cc3e519cf427f0dceb63c30744ec1194c18fa197499cfe3b2385"]}}}
```

Request 3:
`{"id":10,"jsonrpc":"2.0","method":"chain_getFinalizedHead","params":[]}`
Response
```
{"jsonrpc":"2.0","id":10,"result":"0x1474bb43891a2e4f50ecfdf61937ede1d49e7ad188dbfeedec827fe47ad28c15"}
```

That last response triggers polkadotJs to try to fetch the header of the hash contained in the response:
Request
`{"id":11,"jsonrpc":"2.0","method":"chain_getHeader","params":["0x1474bb43891a2e4f50ecfdf61937ede1d49...`
Response
```
{"jsonrpc":"2.0","id":11,"result":null}
```

This `null` value is returned because the provided hash (last known finalized block at the time) was not found in `client.known_blocks`:
https://github.com/paritytech/substrate-lite/blob/39e321212cf89183803008feada85459c3f450d3/bin/wasm-node/rust/src/lib.rs#L317-L323

As far as i can see, `known_blocks` is an `LruCache` with a maximum capacity of 256 which is reached quickly that the library itself starts evicting items. The most probable item to be evicted is `finalized_block` since it is the least used in the short period of time that is required to reach capacity of the cache.

**Comment by tomaka** [comment]
As discussed, this is intended behaviour and not a bug. PolkadotJS is simply too slow to keep up with the chain.

The right fix is to ask the block from another node when it is not known locally.

**Comment by rakanalh** [comment]
Right. To update this issue, the initial thought was that LRU was evicting recent blocks because of access to older blocks moved them to the beginning of the list and moved the finalized block to the back of the list. However, this was wrong because when running the node, it is going to receive lots of `best_block` and `finalized_block` events until the light node is in sync with the full node.

So the fix as far as i can see is 2 fold:
1. Decrease the amount of time required to get in sync with full nodes (warp sync should be in progress for that)
2. In case we receive a query about an old block, @tomaka's suggestion to query for that block from the full node.

**Comment by tomaka** [comment]
I didn't mention it, but 2. is actually pretty hard to do.
If we ask the block from another node, and this node returns an invalid block, then we need to try again with a different node and keep track of the nodes that have returned garbage.

As such, I'd suggest to deal with this later. Item 1. is enough at the moment.

**Comment by tomaka** [comment]
This has been done ages ago.
