### ISSUE TITLE
Consider letting consumers of smoldot wasm node choose what to do with println! messages

### ISSUE THREAD

**Issue by raoulmillais** [paritytech/smoldot#384]
As a consumer of the wasm client what I want to do with these messages will vary.  E.g. If my project uses a logging framework I probably want to send them there instead of directly to the console.

This can be achieved by adding a new logging callback to the config given to start and then calling that here:
https://github.com/paritytech/smoldot/blob/main/bin/wasm-node/javascript/index.js#L184-L189 if 
instead of calling `console.log`.

Happy to submit a PR for this if you think it's a good idea.

**Comment by tomaka** [comment]
I agree that in general it's important to have some indication as to what the node is doing, for example if it manages to connect to other nodes, how busy it is, etc.
I think that logging is the laziest way but also the easiest way to achieve this goal, and yeah I think it makes sense here.

(note that logging is forbidden in the code within `src`, as explained in the coding guide, but can be freely added to what is in `bin`)

**Comment by tomaka** [comment]
Going to close as done in #397
