### ISSUE TITLE
Wasm node: implement JSON-RPC requests multiplexing

### ISSUE THREAD

**Issue by tomaka** [paritytech/smoldot#504]
If the wasm node is embedded in a browser extension, and multiple websites access this extension at the same time, we don't want one of them being able to maliciously DoS the wasm node.

**Comment by raoulmillais** [comment]
I'll have multiplexing in JavaScript ready today to have a look at and for testing.  We can review that as a starting point and decide whether its sensible doing it there at all.  It provides absolutely no DoS protection whatsoever, just blindly rewrites IDs on the fly and cleans up subscriptions on diconnections

**Comment by tomaka** [comment]
Can now be done after https://github.com/paritytech/smoldot/pull/692
The `user_data` can be used in order to do some round robin requests processing.

The details of how to implement this are a bit blurry, but we should stop spawning a new task for every single individual request.

**Comment by tomaka** [comment]
Done in https://github.com/paritytech/smoldot/pull/1036
