### ISSUE TITLE
Don't use batched ed25519 signatures verification

### ISSUE THREAD

**Issue by tomaka** [paritytech/smoldot#53]
I didn't realize that they were broken.

**Comment by marbar3778** [comment]
Not sure how its broken, but a suggestion would be to adopt zip215: https://hdevalence.ca/blog/2020-10-04-its-25519am. https://github.com/ZcashFoundation/ed25519-zebra already implements it and is safe to use in consensus critical areas.

**Comment by burdges** [comment]
Yup https://github.com/dalek-cryptography/ed25519-dalek/pull/117  It becomes safe if [one always uses stricter verification](https://github.com/dalek-cryptography/ed25519-dalek/issues/97), and less nasty if one only ever uses one unique deterministic batch.  In the second case, a node could create a block with all valid signatures that passes validation, but technically contains some invalid signatures.
