### ISSUE TITLE
ed25519-zebra tracking issue

### ISSUE THREAD

**Issue by tomaka** [paritytech/smoldot#587]
https://github.com/paritytech/smoldot/pull/570 has changed the ed25519 library from `ed25519-dalek` to `ed25519-zebra`.
Substrate, however, [hasn't updated](https://github.com/paritytech/substrate/issues/8055).

This means that a bad validator could potentially generate a block header that smoldot considers as valid but Substrate considers as invalid.

I don't think this is a problem as long as smoldot isn't used to produce blocks.
In particular, the light client part doesn't verify whether blocks are correct or not, meaning that it is already possible for a bad validator to generate blocks that smoldot sees as correct but Substrate doesn't.

This issue just serves as a tracking issue to not forget about this difference.

**Comment by burdges** [comment]
It's mostly that 1/3rd of validators could sign for finality in a way that substrate does not believe, but smoldot believes.  All those signatures are still actually signatures however, so governance should manually slash them in this case.

**Comment by tomaka** [comment]
Maybe one risk is that a bad validator could generate a lot of blocks with bad signatures, and "DoS attack" smoldot by flooding it with blocks that it considers valid but Substrate doesn't.

Smoldot, in its memory boundaries, relies on the fact that there's not going to be an infinite amount of blocks signed by validators.
That's normally the case thanks to punishment for equivocation, but if Substrate doesn't consider the signatures as valid, then the malicious actor wouldn't be punished.

**Comment by tomaka** [comment]
cc https://github.com/paritytech/substrate/pull/11781

**Comment by tomaka** [comment]
Closing, as Substrate has now switched to zebra
