### ISSUE TITLE
JSON-RPC requests subscriptions clean up helpers

### ISSUE THREAD

**Issue by tomaka** [paritytech/smoldot#654]
In the context of substrate-connect, multiple web pages "connect" to the substrate-connect extension and send JSON-RPC queries. Substrate-connect in turns sends these JSON-RPC queries to smoldot.

For regular queries, this is rather easier. However, when it comes to subscriptions, substrate-connect has to know which methods are subscription/un-subscriptions, and keep track of which web page has which active subscriptions.
If a web page is closed, substrate-connect needs to send un-subscription requests to smoldot.

In order to avoid having to maintain a list in substrate-connect of JSON-RPC methods that are subscriptions and un-subscrptions, I think that smoldot should handle this natively.

- Instead of passing only the stringified JSON-RPC request, substrate-connect would additionally pass to smoldot an integer representing the web page (or anything similar) that is performing this request.
- The responses sent by smoldot, would also contain this same integer.
- A new function should be added to ask smoldot to clean all subscriptions and cancel all requests corresponding to a certain integer, which substrate-connect would call when a web page closes.

**Comment by expenses** [comment]
How would this 'integer representing the web page' differ from [`request_id`](https://github.com/paritytech/smoldot/blob/91683a38a21146a1f8dfe51dc0d8a2e84eb8cc7c/bin/wasm-node/rust/src/json_rpc_service.rs#L285)?

**Comment by tomaka** [comment]
The `request_id` is chosen by the webpage itself. If there are multiple webpages connect to a single `smoldot`, we must be sure that they don't conflict.

As far as I know, right now `subtrate-connect` currently re-maps all the `request_id`s for this reason, but we should do this in smoldot instead, as explained in the OP.
