### ISSUE TITLE
Error while trying to connect with Substrate Connect (SmoldotProvider) to smoldot

### ISSUE THREAD

**Issue by wirednkod** [paritytech/smoldot#703]
Uncaught TypeError: _randombytes.default is not a function
    at random_get (http://localhost:1234/worker.4dd8c041.js:2608:39)
    at <anonymous>:wasm-function[2689]:0x23bbc2
    at <anonymous>:wasm-function[2683]:0x23b4e1
    at <anonymous>:wasm-function[2676]:0x23b0e5
    at <anonymous>:wasm-function[2673]:0x23acae
    at <anonymous>:wasm-function[2674]:0x23ad87
    at <anonymous>:wasm-function[853]:0x951fb
    at <anonymous>:wasm-function[935]:0xcb82f
    at <anonymous>:wasm-function[135]:0xfb58
    at timer_finished (<anonymous>:wasm-function[1025]:0xe966b)

**Comment by wirednkod** [comment]
Using Parcel v2

**Comment by tomaka** [comment]
I don't know what happens, but here's the code in question:
https://github.com/paritytech/smoldot/blob/e52e812c44eb0e2c105af94be8cccfa468ce900c/bin/wasm-node/javascript/src/bindings-wasi.js#L27
https://github.com/paritytech/smoldot/blob/e52e812c44eb0e2c105af94be8cccfa468ce900c/bin/wasm-node/javascript/src/bindings-wasi.js#L43

**Comment by wirednkod** [comment]
@tomaka Thank you - will have a look at it
