### ISSUE TITLE
REGISTRY: Error: Struct: failed on peers: u64:: Cannot decode value "3" at Struct.js:70

### ISSUE THREAD

**Issue by wirednkod** [paritytech/smoldot#785]
logger.js:63 2021-04-26 13:21:58        REGISTRY: Error: Struct: failed on peers: u64:: Cannot decode value "3"
    at Struct.js:70
    at Array.reduce (<anonymous>)
    at decodeStructFromObject (Struct.js:24)
    at decodeStruct (Struct.js:111)
    at new Struct (Struct.js:132)
    at new <anonymous> (Struct.js:150)
    at new Type (registry.js:340)
    at initType (createType.js:49)
    at createTypeUnsafe (createType.js:69)
    at RpcCore._formatOutput (index.js:394)
apply @ logger.js:63
error @ logger.js:103
createTypeUnsafe @ createType.js:71
_formatOutput @ index.js:394
callWithRegistry @ index.js:262
async function (async)
callWithRegistry @ index.js:261
(anonymous) @ index.js:268
Observable._trySubscribe @ Observable.ts:238
Observable.subscribe @ Observable.ts:219
ConnectableObservable.connect @ ConnectableObservable.ts:44
RefCountOperator.call @ refCount.ts:79
Observable.subscribe @ Observable.ts:214
(anonymous) @ Observable.ts:360
Observable.toPromise @ Observable.ts:358
(anonymous) @ Init.js:86
setInterval (async)
value @ Init.js:85
async function (async)
value @ Init.js:78
Init @ Init.js:152
Getters @ Getters.js:20
ApiBase @ index.js:40
ApiPromise @ index.js:235
create @ index.js:213
Detector.connect @ Detector.ts:33
async function (async)
Detector.connect @ Detector.ts:25
kusama @ index.ts:25
(anonymous) @ index.ts:48
window.onload @ index.ts:50
load (async)
38rfC.regenerator-runtime/runtime @ index.ts:7
newRequire @ index.e935dae2.js:71
(anonymous) @ index.e935dae2.js:120
(anonymous) @ index.e935dae2.js:143
logger.js:63 2021-04-26 13:21:58        RPC-CORE: health(): Health:: createType(Health):: Struct: failed on peers: u64:: Cannot decode value "3"

**Comment by tomaka** [comment]
The error seems to indicate that PolkadotJS fails to decode the result of a `system_health` call.

Here's how smoldot reacts to a `system_health` call:

![image](https://user-images.githubusercontent.com/1412254/116089131-d1d14e00-a6a2-11eb-8af5-f504d4f2c4f8.png)

Here's our upstream Substrate reacts:

![image](https://user-images.githubusercontent.com/1412254/116089267-f4fbfd80-a6a2-11eb-9e05-c10471d5fc79.png)
