### ISSUE TITLE
Add support for GrandPa warp sync for Aura-based chains

### ISSUE THREAD

**Issue by tomaka** [paritytech/smoldot#933]
The functions that are necessary exist in the Aura pallet: https://github.com/paritytech/substrate/blob/a0161f3b224a0607b351ae23b41621b01126a893/primitives/consensus/aura/src/lib.rs#L86-L93

It's just a matter of trying Aura in the warp sync code if the Babe functions are missing.

**Comment by bernardoaraujor** [comment]
@tomaka can you give me some directions so I can try to implement this feature?

**Comment by tomaka** [comment]
https://github.com/paritytech/smoldot/pull/2578 was more or less a pre-requisite and is now done
