### ISSUE TITLE
panicked at 'invalid key', /__w/smoldot/smoldot/src/chain/fork_tree.rs:456:38

### ISSUE THREAD

**Issue by wirednkod** [paritytech/smoldot#996]
Uncaught Error: panicked at 'invalid key', /__w/smoldot/smoldot/src/chain/fork_tree.rs:456:38
    at throw (worker.c1398830.js:2066)
    at <anonymous>:wasm-function[443]:0x4b29e
    at <anonymous>:wasm-function[931]:0xa128b
    at <anonymous>:wasm-function[3363]:0x2b54c5
    at <anonymous>:wasm-function[898]:0xa03d3
    at <anonymous>:wasm-function[897]:0xa03a6
    at <anonymous>:wasm-function[195]:0x1b705
    at <anonymous>:wasm-function[886]:0x9eefb
    at <anonymous>:wasm-function[852]:0x8f925
    at <anonymous>:wasm-function[1096]:0xd68ed

**Comment by tomaka** [comment]
This looks the same as https://github.com/paritytech/smoldot/issues/981
